[accounts.deployer]
mnemonic = "twice kind fence tip vanish import flora remix screen family comfortable generate exit official native arcade commit steel smell mock agent team crucial swim"

[accounts.wallet_1]
mnemonic = "shadow diverse amount license affair example multifield manage annex helix minute exotic ordinary example drive key change audio lazy surface phone arrest deny learn"

[accounts.wallet_2]
mnemonic = "grant rice online decide expert grace credit relief zebra wine evidence fetch basket subtitle crash tragic engine gravity swim alpha drip restore bundle write"
