[project]
name = "starstruck"
description = "StarStacks Perpetual Futures DEX"
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-oracle-v4"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-storage-v4"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.pyth-pnau-decoder-v3"

[[project.requirements]]
contract_id = "SP1CGXWEAMG6P6FT04W66NVGJ7PQWMDAC19R7PJ0Y.wormhole-core-v4"

[[project.requirements]]
contract_id = "SP1HFCRKEJ8BYW4D0E3FAWHFDX8A25PPAA83HWWZ9.dual-stacking-v2_0_2"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts]

[contracts.starstacks-core]
path = "contracts/starstacks-core.clar"
clarity_version = 5
epoch = "latest"

[contracts.proposal-trait]
path = "contracts/proposal-trait.clar"
clarity_version = 5
epoch = "latest"

[contracts.extension-trait]
path = "contracts/extension-trait.clar"
clarity_version = 5
epoch = "latest"

[contracts.collateral-vault]
path = "contracts/collateral-vault.clar"
clarity_version = 5
epoch = "latest"

[contracts.sbtc-token]
path = "contracts/sbtc-token.clar"
clarity_version = 5
epoch = "latest"

[contracts.liquidation-engine]
path = "contracts/liquidation-engine.clar"
clarity_version = 5
epoch = "latest"

[contracts.perpetual-engine]
path = "contracts/perpetual-engine.clar"
clarity_version = 5
epoch = "latest"

[contracts.oracle-adapter]
path = "contracts/oracle-adapter.clar"
clarity_version = 5
epoch = "latest"

[contracts.sbtc-dex]
path = "contracts/sbtc-dex.clar"
clarity_version = 5
epoch = "latest"
