[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high"
balance = 100_000_000_000_000
sbtc_balance = 1_000_000_000

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false

# Contract deployments
[[contracts]]
name = "starstacks-core"
path = "contracts/starstacks-core.clar"

[[contracts]]
name = "proposal-trait"
path = "contracts/proposal-trait.clar"

[[contracts]]
name = "extension-trait"
path = "contracts/extension-trait.clar"

[[contracts]]
name = "sbtc-token"
path = "contracts/sbtc-token.clar"

[[contracts]]
name = "collateral-vault"
path = "contracts/collateral-vault.clar"

[[contracts]]
name = "oracle-adapter"
path = "contracts/oracle-adapter.clar"

[[contracts]]
name = "sbtc-dex"
path = "contracts/sbtc-dex.clar"

[[contracts]]
name = "perpetual-engine"
path = "contracts/perpetual-engine.clar"

[[contracts]]
name = "liquidation-engine"
path = "contracts/liquidation-engine.clar"

# Pox stacking orders
[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_1"
slots = 2
btc_address = "mr1iPkD9N3RJZZxXRk7xF9d36gffa6exNC"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_2"
slots = 2
btc_address = "muYdXKmX9bByAueDe6KFfHd5Ff1gdN9ErG"

[[devnet.pox_stacking_orders]]
start_at_cycle = 1
duration = 10
auto_extend = true
wallet = "wallet_3"
slots = 2
btc_address = "mvZtbibDAAA3WLpY7zXXFqRa3T4XSknBX7"
